// <auto-generated />
using System;
using CalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculatorAPI.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20260622060238_AddSessionIdColumnOnly")]
    partial class AddSessionIdColumnOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculatorAPI.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("OperandA")
                        .HasColumnType("double precision")
                        .HasColumnName("operand_a");

                    b.Property<double>("OperandB")
                        .HasColumnType("double precision")
                        .HasColumnName("operand_b");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_id");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<double>("Result")
                        .HasColumnType("double precision")
                        .HasColumnName("result");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("calculations", (string)null);
                });

            modelBuilder.Entity("CalculatorAPI.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("CalculatorAPI.Models.Calculation", b =>
                {
                    b.HasOne("CalculatorAPI.Models.Operation", "Operation")
                        .WithMany("Calculations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CalculatorAPI.Models.Operation", b =>
                {
                    b.Navigation("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
